name: antique_id
description: "An AI-powered antique identification app that helps you identify and learn about antiques, artifacts, and collectibles."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.8
  fimber: ^0.7.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  hugeicons: ^0.0.11
  iconsax: ^0.0.8
  lucide_icons: ^0.257.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  path_provider: ^2.1.5
  http: ^1.4.0
  path: ^1.9.1
  rename_app: ^1.6.3
  flutter_launcher_icons: ^0.14.4
  purchases_flutter: ^8.10.4
  purchases_ui_flutter: ^8.10.4
  in_app_review: ^2.0.8
  crypto: ^3.0.3
  connectivity_plus: ^6.0.5
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/
    - assets/onboarding/onboarding_1.svg
    - assets/onboarding/onboarding_2.svg
    - assets/onboarding/onboarding_3.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
